# Generated by Django 3.0.4 on 2020-03-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='bud',
        ),
        migrations.AlterField(
            model_name='budget',
            name='budgets',
            field=models.BigIntegerField(),
        ),
    ]
