# Generated by Django 3.0.4 on 2020-03-07 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CMapp', '0002_auto_20200306_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='lieu_naissance',
            new_name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='depense',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='tel',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pseudo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
