# Generated by Django 3.0.4 on 2020-03-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMapp', '0003_auto_20200307_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depenses',
            new_name='Depense',
        ),
    ]
