# Generated by Django 3.0.4 on 2020-03-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMapp', '0003_auto_20200311_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budgets',
            field=models.BigIntegerField(null=True),
        ),
    ]
