# Generated by Django 3.0.4 on 2020-03-07 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CMapp', '0004_auto_20200307_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
